### ISSUE TITLE
Mentor Registration for First Day Nodeschool, Wednesday, Sept 14th 2016

### ISSUE THREAD

**Issue by pcuci** [nodeschool/montreal#15]
Temps Libre is hosting us Sept 14, 5:30 to 8:30pm, address is 5605 ave. de Gaspé, #106.

Comment to get involved or ask questions.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event
  - Having also completed elective workshoppers is a great bonus :-)
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page
- Arrive 30 minutes early so we can get setup and connect with peer mentors

Confirmed mentors:
- [x] @nicolasgere
- [x] @shawnthompson
- [x] @CassieLR
- [x] @ajmas
- [x] @HarrisRobin
- [x] @vicneanschi
- [x] @therazakhan
- [x] @jeffmarshall

Organizers and volunteers:
- [x] @pcuci
- [x] @CassieLR
- [x] @David-Ro 

Next workshops:
- [x] @sayar

**Comment by ghost** [comment]
I would like to be a mentor, have years of experience in NodeJS

**Comment by David-Ro** [comment]
```
                                                                                  Fantastic. I'm sending this to Paul and Cassie too. David Rowley                                                                                                                                                                                                                                                                                                                                         
```

**Comment by pcuci** [comment]
@therazakhan thx Reza - got you listed as mentor, see you Wednesday - plz send a PR with a photo, and  review the [On Being a Mentor wiki](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices#on-being-a-mentor)

**Comment by pcuci** [comment]
Hi team - a big thank you for being great mentors!

Feedback was overwhelmingly positive: 

![](http://i.imgur.com/fv1U5hZ.png)

We couldn't have done it without you!

RSVP as mentor for 2nd Day NodeSchool: #41
