### ISSUE TITLE
Mentor Registration for 2nd Day Nodeschool, Tuesday, Oct 25th 2016

### ISSUE THREAD

**Issue by pcuci** [nodeschool/montreal#41]
Temps Libre is hosting us Tuesday, October 25th, 5:00 to 8:30pm, address is 5605 ave. de Gaspé, #106. Specifically, @jeffmarshall is our host since he's based at TL and can therefore secure the place for free. Thanks, @jeffmarshall !

We'll charge NodeSchoolers $5 for refreshments, and any remaining cash goes to https://github.com/nodeschool/organizers/issues/369

Comment to get involved or ask questions.

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event
  - Having also completed elective workshoppers is a great bonus :-)
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page
- Arrive 30 minutes early so we can get setup and connect with peer mentors

Confirmed mentors:
- [x] @jeffmarshall
- [ ] @nicolasgere
- [ ] @sayar 
- [ ] @shawnthompson
- [x] @ajmas
- [ ] @HarrisRobin
- [x] @vicneanschi
- [ ] @therazakhan
- [x] @matchai
- [x] @adelporte

Organizers:
- [x] @pcuci
- [x] @CassieLR
- [x] @David-Ro

Other notes:

Based on the feedback received at last event - i.e.: intense coding but no food :sob: - we decided to charge $5 for this event. In the future, a sponsor may cover the food costs. Both @jeffmarshall and @CassieLR are prospecting sponsors, so if you know anyone please let us know!

If we're lucky and sponsor jumps on board, we can reimburse the participants. Otherwise, better snacks next time. :smile:

**Comment by matchai** [comment]
I'll join in again this time!

**Comment by vicneanschi** [comment]
Count on me.

**Comment by ajmas** [comment]
Will depend on the day.

**Comment by sayar** [comment]
Same for me... I'm travelling quite a bit in October so my participation will depend on the date.

**Comment by shawnthompson** [comment]
Same here, it depends on the day. But if I'm in town, I'm in!

**Comment by pcuci** [comment]
Ok, gang - we're set for Tuesday Oct 25th, please confirm your presence.

I just did a quick estimate on the opportunity cost for your time, and we're looking at $100/h \* 2h \* 10 mentors = $2000+ value invested into the community by you all, each month.

Wow. Thank you!

**Comment by vicneanschi** [comment]
Confirmed

**Comment by vicneanschi** [comment]
It's actually Monday in my calendar

**Comment by ajmas** [comment]
It's meant to be Tuesday 25th October.

**Comment by ajmas** [comment]
I am confirmed.

**Comment by sayar** [comment]
I am speaking at meetup on Tuesday October 25th already :(

**Comment by pcuci** [comment]
Tons of thoughtful learning, helpful mentors - thank you all!

![image](https://cloud.githubusercontent.com/assets/2169849/19712483/53112c3a-9b0c-11e6-85b3-4036922e75b7.png)
