### ISSUE TITLE
Team projects

### ISSUE THREAD

**Issue by pcuci** [nodeschool/montreal#42]
Section or page displaying active projects

Criteria for acceptance:
- As a ______, I need _______ such that _______ user story - as main feature proposal for NodeSchool community to work on (not the whole app, just one aspect)
- Uses JavaScript, preferably Node
- Diverse types of help needed

**Comment by David-Ro** [comment]
This is clear. I think you can make it a recurring communication (maybe a signature line) in all outgoing messages to the broadest community.

**Comment by pcuci** [comment]
https://pcuci.github.io/nodeschool-theams/ - here's an early prototype, forked @jlord's `hack-spots`, might work for tracking themed teams' projects for NodeSchoolers to practice on real community projects.

What details do we need from learning teams?

**Comment by pcuci** [comment]
First draft of pages integrated and working, using hackspots to connect to the shared google spreadsheet
