### ISSUE TITLE
Pop-up Node Hangout

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/montreal#47]
Date: December 3rd, 15:00
Where: 1030 Cherrier Est, le bistro Tôt ou Tard

------
Original post: 

I hear that the next Nodeschool meeting is planned for January. As that is a ways away, I'm wondering if anyone would be interested in meeting up in a café or something and hacking away for a few hours this or next weekend. Nothing organized, no stickers, workshoppers if you like; mostly just a place to meet other people in the community and talk about our {side}projects. 

Not sure if this is the best place to post this request, but figured it wouldn't hurt. 

Anyone interested?

**Comment by ajmas** [comment]
+1 Can't do this weekend, but during the week I could.

**Comment by David-Ro** [comment]
yes.

**Comment by David-Ro** [comment]
"... meeting ... next weekend" -- make it afternoon, weekend Dec 3, 4. 
Location: I can give you places if you give me a postal code range.

**Comment by RichardLitt** [comment]
December 3rd, 3pm. I'm in the Plateau, but the cafes fill up in the weekends. Thoughts anyway?

**Comment by David-Ro** [comment]
I know Montreal better than you do. Let me have the approximate postal code that you like best. Or two of them. Or three. 
‎
Examples of places. Near...‎
LaFontaine Park: the Tot ou Tard café bistro. It's easy to reserve a table for 6 (or 8 or...)
Mile End: Navarino café, opposite the YMCA 
‎

**Comment by RichardLitt** [comment]
I am at H2W2H1, near McGill. Can bike anywhere, though.

**Comment by David-Ro** [comment]
Easiest bestest fast choice is the one at 1030 Cherrier East, le bistro Tôt ou Tard, Because of its high-speed free WiFi, low-cost full breakfasts served until 4pm, calm service, location known to many. Bike racks in front. Can have a booth or alcove table.

**Comment by David-Ro** [comment]
I've checked around, I think it'll be possible to have a few people. So we could think of a theme or focus. (e.g. IPFS, or some personal project, or a Meteor slant, or

**Comment by RichardLitt** [comment]
Sounds good to me! Personal projects sound good to me. Happy to help hack on IPFS, too!

**Comment by pcuci** [comment]
Let's talk NodeSchool 2017 projects (main theme)

@RichardLitt - would be cool to hear about your experiences organizing NodeSchool in Chiang Mai

cc: @CassieLR @matchai @HarrisRobin

**Comment by harrisrobin** [comment]
I'll be there! 
1030 Cherrier East is confirmed?

**Comment by David-Ro** [comment]
Corner of Parc LaFontaine Avenue. 
(Amherst Street)‎                                                                                                                                                                                                                                                                                                                                                                                               
(Edited after looking twice. I responded from an old BB10 phone)

**Comment by RichardLitt** [comment]
@David-Ro Looks like there's an issue with your email responder, that JSON probably shouldn't be there. 

1030 Cherrier Est confirmed. See you there.

**Comment by RichardLitt** [comment]
Can we meet at 12:00? If there is an all day breakfast, we might as well get there soon enough to enjoy it. :)

**Comment by harrisrobin** [comment]
@RichardLitt I'll probably be there before 12.

**Comment by David-Ro** [comment]
At noon "Tot ou Tard" café-restaurant will be packed, seriously crowded. Even on a cold day in December. 
* The alternative, for a place to get real work done around 11:30, noon, 1pm, 2pm, is to use "Espace MixMix" 936 Rachel Street East, H2J 2J2 - there is food there (but not full meals) and it's never crowded.

At Tot ou Tard, either go at 11am (with a reserved table) or mid-afternoon (without reserving a table).

**Comment by RichardLitt** [comment]
Ah, ok. Let's keep the official meeting at three, then. I'll be at Espace MixMix from around 1pm, and head to Tot ou Tard at around 3.

**Comment by David-Ro** [comment]
MixMix has WiFi and electrical outlets. I was there today.

**Comment by RichardLitt** [comment]
Thanks all! Great meeting you and chatting about Node. 

@pcuci Post up your notes somewhere! Looking forward to making nodeschool better here. For now, closing this out.

**Comment by harrisrobin** [comment]
@RichardLitt any chance of getting your email/facebook so that i can contact you about meeting up for a more linguistics-oriented discussion before you leave? :P
Perhaps @David-Ro would like to join as well!

**Comment by RichardLitt** [comment]
I'm on Twitter as `@richlitt`. Email is first.last at gmail. :)

**Comment by pcuci** [comment]
Perify, MVP^2, BVP - mob/collective hacking grouping

# Top Project/co-tutorials
Cookbooks to be coded together at next NodeSchools
1. Jekyll site, with newsletter
2. Sell your time with Stripe, end-to-end integration with payments (alt: PayPal, Shopfiy)
3. Real-time live/crowd Q&A
4. Link sharing up-voting (hackernews, telescope, reddit clone)
4. No projector slides, beamed to phones, pause, react with feedback tracking

# Other Project ideas
1. IPFS decentralized primer
2. Pub-sub topic subscribing system
3. Chat npm package ready to use in own app
4. Collective calendar (on top of IPFS), un-owned

Primary goal is to learn to work with one-another, pseudo teams, coerced contributing, mob programming


# Resources
- http://todomvc.com/, https://www.meteor.com/tutorials (ToDo one to start, takes 3 hours on your own)
- https://themeteorchef.com/recipes/
