### ISSUE TITLE
Mentor Registration NodeSchool, Wed, Feb 22th 2017 at OVH

### ISSUE THREAD

**Issue by pcuci** [nodeschool/montreal#49]
[OVH](https://www.ovh.com/ca/en/dlp/) is hosting us Wed, Feb 22nd, 5:30 to 8:30pm :clap: 

Address is 1801 Avenue McGill College #800, Montréal, QC H3A 1Z4

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event
  - Having also completed elective workshoppers is a great bonus :-)
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page
- Arrive 15 minutes early to help setup and connect with peer mentors

Confirmed mentors:
- [x] @nicolasgere
- [ ] @sayar 
- [x] @shawnthompson
- [x] @ajmas
- [ ] @HarrisRobin
- [x] @vicneanschi
- [ ] @therazakhan
- [x] @matchai
- [ ] @adelporte
- [x] @RichardLitt 

Organizers:
- [x] @pcuci
- [ ] @CassieLR
- [x] @David-Ro

Comment to get involved or ask questions.

Thanks much for sharing your time and skill!

**Comment by vicneanschi** [comment]
I'm available.

**Comment by RichardLitt** [comment]
Thanks @pcuci. Let me know if I can help out in any other way before hand!

**Comment by pcuci** [comment]
@RichardLitt - we're mixing up the format with 2-3 minute lightning talks, if you want to show a project of yours quickly

@nicolasgere is showing https://www.npmjs.com/package/graphql-ts and I plan to show some meteor

Updated the slides: https://docs.google.com/presentation/d/1RPqAu5iqWNosObRoDU9S1a0Q8z4xcQ1AaIpVecRBOW4

**Comment by RichardLitt** [comment]
I'd be happy to. I'll talk about [standard-readme](//github.com/RichardLitt/standard-readme).

**Comment by shawnthompson** [comment]
I've been working **slowly** on building a base site using NodeJS, grunt, bower, sass and some other packages.

https://github.com/shawnthompson/base-node-template 

I can talk about what I'm trying to do and why I'm trying to do it.

I think I'll add @RichardLitt's standard-readme to it 👍

**Comment by pcuci** [comment]
Gang - did any of you take photos at this last event?

I keep forgetting to do the propaganda work, heh
