### ISSUE TITLE
Mentor Registration NodeSchool, Tue, Apr 18th 2017 at OVH

### ISSUE THREAD

**Issue by pcuci** [nodeschool/montreal#51]
[OVH](https://www.ovh.com/ca/en/dlp/) is hosting us again Tue, Apr 18th, 5:30 to 8:30pm with :pizza: this time! :clap:

Address is 1801 Avenue McGill College #800, Montréal, QC H3A 1Z4

Mentors should:
- Have already completed the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) beforehand
  - Elective workshoppers is a great bonus :-)
- Review the [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page
- Arrive 15 minutes early to connect with the other mentors

Confirmed mentors:
- [x] @RichardLitt *
- [x] @matchai *
- [ ] @nicolasgere
- [ ] @sayar 
- [ ] @shawnthompson
- [ ] @ajmas *
- [x] @HarrisRobin
- [ ] @vicneanschi
- [ ] @therazakhan
- [ ] @adelporte
- [ ] @jeffmarshall
- [ ] @ziad-saab
- [ ] @marekweb
- [ ] @CassieLR *
- [ ] @fed135
- [ ] @ehren123
- [x] @pcuci *
- [x] @David-Ro *
- [ ] ___
- [ ] ___ (+ photographer role)

_*_ = also organizer/contributor

Comment to get involved or ask questions.

Thanks much for sharing your time and skill!

See #14 for day-of logistics - how should we change/evolve the format this time?

**Comment by pcuci** [comment]
Who's available next Tuesday? Please RSVP here, in the comments!

Got a 2-4 minute demo of a project you're working on, or an a quick update? We'll do lighning talks again (super short) before hacking

**Comment by ajmas** [comment]
I'll be out of town, unfortunately.

**Comment by ziad-saab** [comment]
I'll be here. I want to do a lightning pres to show a tiny vanilla JavaScript game that uses only `<canvas>`.

**Comment by RichardLitt** [comment]
I'll be here. Could talk about maintainer.io or something.

**Comment by matchai** [comment]
I'll be there. I've got an interactive lightning talk on Javascript typing and coercion.

**Comment by David-Ro** [comment]
Tomorrow Tuesday first day back after long weekend off 
@marekweb @CassieLR @fed135 @ehren123 @sayar 
See you 5:30pm or be square. 
OVH is 8th floor, corner McGill College and deMaisonneuve, in Eaton Centre building.

**Comment by ziad-saab** [comment]
Change of plan, won't be able to make it. My building decided to have their co-owner meeting on that evening. Have fun!!

**Comment by David-Ro** [comment]
Tomorrow Tuesday first day back after long weekend off
@marekweb @CassieLR @fed135 @ehren123 @sayar
See you 5:30pm or be square.
OVH is 8th floor, corner McGill College and deMaisonneuve, in Eaton Centre building.

**Comment by David-Ro** [comment]
Tomorrow Tuesday first day back after long weekend off
@therazakhan @adelporte
See you 5:30pm or be square.
OVH is 8th floor, corner McGill College and deMaisonneuve, in Eaton Centre building.
