### ISSUE TITLE
Tues June 6th at OVH. NodeSchool

### ISSUE THREAD

**Issue by David-Ro** [nodeschool/montreal#60]
[OVH](https://www.ovh.com/ca/en/dlp/) is hosting us again Tue, June 6th, 5:20 to 8:25pm with :pizza: this time! :clap:
Address is still 1801 Avenue McGill College #800, Montréal, QC H3A 1Z4

Mentors 
- arrive 10 minutes early, to connect with other mentors
- know the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) beforehand
- know elective workshoppers is good too :-)
- review [Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page

Confirmed mentors:
- [x] @CassieLR *
- [x] @matchai *
- [x] @sophiedeziel
- [x] @ziad-saab
- [x] @ajmas *
- [x] @ruyadorno 
- [x] @fed135
- [ ] @ehren123
- [ ] @sayar 
- [ ] @shawnthompson
- [ ] @HarrisRobin
- [ ] @vicneanschi
- [ ] @pcuci *
- [x] @David-Ro *
- [ ] @RichardLitt *
- [ ] @therazakhan
- [ ] @adelporte
- [ ] @jeffmarshall
- [ ] @nicolasgere
- [ ] @marekweb
- [ ] ___
- [ ] ___ (+ photographer role)
_*_ = also organizer/contributor

Comment to get involved or ask questions.
Thanks everyone for sharing your time skill and talk!
See #14 for day-of logistics: change/evolve format?

**Comment by RichardLitt** [comment]
Thanks @David-Ro! Gonna have to help out remotely this time. I'll remove myself from the website, for now, seems convenient. Not sure when I'll be back - hopefully in June or July.

**Comment by RichardLitt** [comment]
Done in f2a28574e5fd500ba967c9d39ca4bf239137e803.

**Comment by vicneanschi** [comment]
@David-Ro I'll be there.

**Comment by ziad-saab** [comment]
me too :)

**Comment by fed135** [comment]
I'll be there (as mentioned in gitter)

**Comment by David-Ro** [comment]
Got it. Tks                                                                                                                                                                                                                From: Frederic CharetteSent: Tuesday, June 6, 2017 2:20 PMTo: nodeschool/montrealReply To: nodeschool/montrealCc: David Rowley 514; MentionSubject: Re: [nodeschool/montreal] Tues June 6th at OVH. NodeSchool (#60)I'll be there (as mentioned in gitter)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nodeschool/montreal","title":"nodeschool/montreal","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nodeschool/montreal"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fed135 in #60: I'll be there (as mentioned in gitter)"}],"action":{"name":"View Issue","url":"https://github.com/nodeschool/montreal/issues/60#issuecomment-306573537"}}}
