### ISSUE TITLE
Publicize event

### ISSUE THREAD

**Issue by RichardLitt** [nodeschool/montreal#75]
- [ ] Facebook event
- [ ] Twitter
- [ ] Newsletter
- [x] Meetup.com

Anywhere else we need to do this? Anyone want to help out?

**Comment by RichardLitt** [comment]
According to #44:

- https://www.facebook.com/search/str/nodeschool+learnyounode/keywords_top - see where we've published in the past
- Montreal + Startups: https://www.facebook.com/groups/montreal.startup.people/
- McGill Dobson: https://www.facebook.com/groups/DobsonCentreCommunity/
- UP Montreal: https://www.facebook.com/groups/startup.montreal.techstars/
- Hack Concordia: https://www.facebook.com/groups/hackconcordia/
- HHMTL: https://www.facebook.com/HHMTL

Anyone want to help grab these? @David-Ro? @pcuci? @fed135 or @matchai?

**Comment by kareniel** [comment]
I noticed there's no Facebook event; I'd be happy to take care of it but I don't have access.

**Comment by RichardLitt** [comment]
I don't have access, either (I don't use Facebook).

**Comment by RichardLitt** [comment]
Great job, all. :)
