### ISSUE TITLE
Large empty block at the top of the website

### ISSUE THREAD

**Issue by matchai** [nodeschool/montreal#76]
![image](https://user-images.githubusercontent.com/4658208/33296616-9020e26e-d3aa-11e7-8bd1-0eb71cab65f1.png)

It looks like some of the content on the right side is causing the main main content of the site to shift down. It appears removing the mailing list or the Facebook iframe fixes the problem.

Anyone with CSS know-how want to give this a shot?

**Comment by RichardLitt** [comment]
I actually liked this and thought it was a design feature. Is it not?

**Comment by matchai** [comment]
If you compare our site to the one we initially forked, you can definitely tell it's not intended: https://nodeschool.io/toronto/ 😛 

I do think we would benefit from pulling in the current toronto nodeschool website and tweaking it to suit our needs. They've got a lot of nice design elements, and our own site has become cluttered with content that has been added a while back. From there, we can start adding our own features (i18n).

**Comment by ajmas** [comment]
I was struggling with whether the navigation bar that disappeared on the side was intentional. Though, it should be noted that the navigation bar version doesn't work too well on mobile, so we should consider that when resolving things.
