### ISSUE TITLE
'How do I install Node' FAQ entry seems very Mac specific

### ISSUE THREAD

**Issue by ajmas** [nodeschool/montreal#87]
The 'How do I install Node' FAQ entry seems very Mac specific, we should probably deal with this question in a multi-platform way.

There is a page here on installing Node via package installers:

https://nodejs.org/en/download/package-manager/

**Comment by matchai** [comment]
Seeing the high number of Windows users that come to NodeSchool, maybe we should instead simply link to the home page and suggest attendees install the current version? https://nodejs.org/en/

**Comment by matchai** [comment]
We can alternatively link to https://nodejs.org/en/download/current/

**Comment by ajmas** [comment]
Or maybe just, add: "if you don't want to use a package manager, then you can use an [installer](https://nodejs.org/en/)"?

**Comment by matchai** [comment]
I would probably suggest the installer first, since many users might not know what a package manager is: "To install NodeJS, download the [installer](https://nodejs.org/en/), or use the [package manger](https://nodejs.org/en/download/package-manager/) of your choice."
