### ISSUE TITLE
Change color scheme

### ISSUE THREAD

**Issue by pcuci** [nodeschool/montreal#9]
Follow-up on #2, develop a unique identity for NodeSchoolMTL, different-looking from NodeSchoolToronto

**Comment by ajmas** [comment]
What colours do we want to use for Montreal? Blues, greens, yellows? Being in Quebec I tempted by blue and white :-)

**Comment by ajmas** [comment]
Maybe this #4060ba ?

**Comment by ajmas** [comment]
Provided a candidate colour change for review
